id: ADA967EEC
base_file: f6B63.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - nl
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:06.485651
  last_modified_at: 2022-05-30 20:46:06.485654
