id: ADA967EEC
base_file: fA1CC.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:06.500066
  last_modified_at: 2022-05-30 20:46:06.500069
