id: ADA967EEC
base_file: f3BAB.txt
type: translation
source_metadata:
  languages:
  - en
  - es
  - fr
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:06.471937
  last_modified_at: 2022-05-30 20:46:06.471940
