id: ADA967EEC
base_file: f73A3.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:06.488298
  last_modified_at: 2022-05-30 20:46:06.488300
