id: ADA967EEC
base_file: f755D.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 20:46:06.489486
  last_modified_at: 2022-05-30 20:46:06.489489
